name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

        include:
        - os: windows-latest
          cxx: cl
          target-os: windows
          target-arch: [x86, x86_64]

        - os: ubuntu-latest
          cxx: clang
          target-os: linux
          target-arch: [x86_64]

        - os: macos-latest
          cxx: g++
          target-os: macos
          # target-arch: [aarch64] ?
    

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v2
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.target-os }} == windows
      with:
        arch: ${{ matrix.target-arch }}
    
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: configure
      run: meson --buildtype=release bin
      env:
        CXX: ${{ matrix.cxx }}
    
    - name: compile
      run: meson compile -C bin