name: build

on: 
  push:
  release:
     types:
       - published

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          # Windows x86
          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'x86_64'
            msvc-target-arch: 'x86_64'

          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'x86'
            msvc-target-arch: 'amd64_x86'

          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'arm'
            cross-file: 'cross/windows-arm.txt'
            msvc-target-arch: 'amd64_arm'

          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'aarch64'
            cross-file: 'cross/windows-aarch64.txt'
            msvc-target-arch: 'amd64_arm64'


          # Linux
          - os: ubuntu-latest
            os-fancy-name: 'linux'
            target-arch: 'x86_64'

          - os: ubuntu-latest
            os-fancy-name: 'linux'
            target-arch: 'x86'
            cross-file: 'cross/linux-x86.txt'
            apt-packages: 'g++-i686-linux-gnu'

          - os: ubuntu-latest
            os-fancy-name: 'linux'
            target-arch: 'arm'
            cross-file: 'cross/linux-arm.txt'
            apt-packages: 'g++-arm-linux-gnueabi'

          - os: ubuntu-latest
            os-fancy-name: 'linux'
            target-arch: 'aarch64'
            cross-file: 'cross/linux-aarch64.txt'
            apt-packages: 'g++-aarch64-linux-gnu'
          

          # MacOS (i actualy dont know if this is working xd, i dont have a mac, it would be nice if someone would test this on mac.)
          - os: macos-latest
            os-fancy-name: 'macos'
            target-arch: 'x86_64'
    

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os-fancy-name == 'windows'
      with:
        arch: ${{ matrix.msvc-target-arch }}
    
    - uses: actions/setup-python@v3
      with:
        cache: 'pip'
    
    - name: install meson and ninja.
      run: pip install meson ninja -r requirements.txt
    

    - uses: hendrikmuhs/ccache-action@v1
      if: matrix.os-fancy-name != 'windows'
      with:
        key: ${{ matrix.os }}-${{ matrix.target-arch }}


    - name: (linux) install apt packages.
      if: matrix.os-fancy-name == 'linux' && matrix.apt-packages != null
      run: sudo apt update -y && sudo apt install ${{ matrix.apt-packages }} -y


    - name: configure.
      if: matrix.cross-file == null
      run: meson --buildtype=release bin
    
    - name: (cross) configure.
      if: matrix.cross-file != null
      run: meson --buildtype=release bin --cross-file ${{ matrix.cross-file }}
    

    - name: compile.
      run: meson compile -C bin -j 10


    - uses: actions/upload-artifact@v3
      if: github.event_name != 'release'
      with:
        name: markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch }}
        path: |
          bin/markdown-help.exe
          bin/markdown-help

    
    - name: (windows) bundle.
      if: (matrix.os-fancy-name) == 'windows' && (github.event_name == 'release')
      run: tar -czf markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch }}.zip bin\markdown-help.exe

    - name: (linux / mac) bundle.
      if: (matrix.os-fancy-name) != 'windows' && (github.event_name == 'release')
      run: tar -czf markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch }}.tar.gz bin/markdown-help

    
    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        files: 'markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch }}.zip;markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch }}.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}