name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

        include:
        - os: windows-latest
          cxx: clang

        - os: ubuntu-latest
          cxx: clang++

        - os: macos-latest
          cxx: g++
          

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: ilammy/msvc-dev-cmd@v1.10.0
      if: ${{ matrix.os }} == windows-latest
    
    - run: pip install meson ninja

    - name: configure
      run: meson --buildtype=release bin
      env:
        CXX: ${{ matrix.cxx }}
    
    - name: compile
      run: meson compile -C bin