name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target-arch: 'x86_64'

          - os: windows-latest
            target-arch: 'x86'


          - os: ubuntu-latest

          - os: macos-latest
    

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v2
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: ${{ matrix.target-arch }}
    
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - run: g++ -dumpmachine
    - run: clang -dumpmachine

    - name: configure
      run: meson --buildtype=release bin
    
    - name: compile
      run: meson compile -C bin