name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'x86_64'
            target-arch-fancy-name: 'x86_64'

          - os: windows-latest
            os-fancy-name: 'windows'
            target-arch: 'x86'
            target-arch-fancy-name: 'x86'


          - os: ubuntu-latest
            os-fancy-name: 'linux'
            target-arch: 'x86_64'
            target-arch-fancy-name: 'x86_64'

          - os: macos-latest
            os-fancy-name: 'macos'
            target-arch: 'x86_64'
            target-arch-fancy-name: 'x86_64'
    

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v2
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: ${{ matrix.target-arch }}
    
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: configure
      run: meson --buildtype=release bin
    
    - name: compile
      run: meson compile -C bin

    - uses: actions/upload-artifact@v2
      with:
        name: markdown-help-${{ matrix.os-fancy-name }}-${{ matrix.target-arch-fancy-name }}
        path: bin/markdown-help+.exe