name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

        include:
        - os: windows-latest
          env:
            CXX: cl

        - os: ubuntu-latest
          env:
            CXX: g++

        - os: macos-latest
          env:
            CXX: clang++
          

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: ilammy/msvc-dev-cmd@v1.10.0
      if: ${{ matrix.os }} == windows-*
    
    - run: pip install meson ninja

    - name: configure
      run: meson --buildtype=release bin
    
    - name: compile
      run: meson compile -C bin